### ISSUE TITLE
Step count fails for Newcastle subject 29 gene active 

### ISSUE THREAD

**Issue by angerhang** [OxWearables/stepcount#15]
```
Reading file... Done! (3.75s)
Converting to dataframe... Done! (0.24s)
Getting stationary points... Done! (0.71s)
Gravity calibration... Done! (1.09s)
Nonwear detection... Done! (0.95s)
Resampling... Done! (0.23s)
Traceback (most recent call last):
  File "/Users/hangy/opt/miniconda3/envs/step_count/bin/stepcount", line 8, in <module>
    sys.exit(main())
  File "/Users/hangy/opt/miniconda3/envs/step_count/lib/python3.9/site-packages/stepcount/stepcount.py", line 55, in main
    model = load_model(args.model_path or model_path, args.model_type, check_md5, args.force_download)
  File "/Users/hangy/opt/miniconda3/envs/step_count/lib/python3.9/site-packages/stepcount/stepcount.py", line 286, in load_model
    return joblib.load(pth)
  File "/Users/hangy/opt/miniconda3/envs/step_count/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 587, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/Users/hangy/opt/miniconda3/envs/step_count/lib/python3.9/site-packages/joblib/numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "/Users/hangy/opt/miniconda3/envs/step_count/lib/python3.9/pickle.py", line 1212, in load
    dispatch[key[0]](self)
KeyError: 255
(step_count) ha
```

The data can be download here https://zenodo.org/record/1160410#.Y__0Gi-l1qs

**Comment by chanshing** [comment]
What version of `joblib` are you using? File 14 worked for me: 
![image](https://user-images.githubusercontent.com/5551642/223144149-65e00392-4a6f-42b6-87a3-420c17d12358.png)

But something is going on with file 29, it's getting stuck. I'll keep looking...
