### ISSUE TITLE
 AttributeError: 'float' object has no attribute 'round'

### ISSUE THREAD

**Issue by desPets** [OxWearables/stepcount#23]
Getting the following error when trying to run using a csv file with data

Traceback (most recent call last):
  File "anaconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "anaconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "Scripts\stepcount.exe\__main__.py", line 7, in <module>
  File "anaconda3\lib\site-packages\stepcount\stepcount.py", line 70, in main
    summary = summarize(Y, model.steptol)
  File "anaconda3\lib\site-packages\stepcount\stepcount.py", line 147, in summarize
    daily_med = daily.median().round()
AttributeError: 'float' object has no attribute 'round'

**Comment by smallsr** [comment]
Hi @desPets. Can you confirm which version you're using? @chanshing has just released an update (2.1.3) with bug fixes that may address this.

**Comment by desPets** [comment]
Updated to latest version 2.1.3. and now it works! thanks

**Comment by smallsr** [comment]
Fantastic! Thanks for trying out our tools!
