### ISSUE TITLE
AttributeError: 'Timedelta' object has no attribute 'astype'

### ISSUE THREAD

**Issue by muschellij2** [OxWearables/stepcount#49]
# Description
Failure in `actipy.process` command when estiamting non-wear periods on line
https://github.com/OxWearables/stepcount/blob/794b79e56e8314602e02ca61ca27d324ff26c5df/src/stepcount/stepcount.py#L358
This is due to a failure of `detect_nonwear` https://github.com/OxWearables/stepcount/blob/794b79e56e8314602e02ca61ca27d324ff26c5df/src/stepcount/stepcount.py#L362

# File to Reproduce
[P30_wrist100.csv.gz](https://github.com/OxWearables/stepcount/files/13834398/P30_wrist100.csv.gz)
This is from https://ora.ox.ac.uk/objects/uuid:19d3cb34-e2b3-4177-91b6-1bad0e0163e7.  

```bash
$ conda activate stepcount
(stepcount) $ stepcount P30_wrist100.csv.gz 
```

And the resulting output is: 
```
actipy/processing.py:294: UserWarning: Skipping calibration: Insufficient stationary samples: 1 < 50
  warnings.warn(f"Skipping calibration: Insufficient stationary samples: {len(xyz)} < {calib_min_samples}")
Gravity calibration... Done! (0.04s)
Traceback (most recent call last):
  File "/Users/johnmuschelli/miniconda3/envs/stepcount/bin/stepcount", line 8, in <module>
    sys.exit(main())
  File "/Users/johnmuschelli/miniconda3/envs/stepcount/lib/python3.9/site-packages/stepcount/stepcount.py", line 48, in main
    data, info = read(args.filepath, resample_hz, verbose=verbose)
  File "/Users/johnmuschelli/miniconda3/envs/stepcount/lib/python3.9/site-packages/stepcount/stepcount.py", line 356, in read
    data, info = actipy.process(
  File "/Users/johnmuschelli/miniconda3/envs/stepcount/lib/python3.9/site-packages/actipy/reader.py", line 144, in process
    data, info_nonwear = P.detect_nonwear(data)
  File "/Users/johnmuschelli/miniconda3/envs/stepcount/lib/python3.9/site-packages/actipy/processing.py", line 201, in detect_nonwear
    stationary_segment_ids
AttributeError: 'Timedelta' object has no attribute 'astype'
```

**Comment by muschellij2** [comment]
Upgrading to actipy 3.0.5 resolved this issue - likely should make this a higher req?
