### ISSUE TITLE
TypeError: NumPy boolean array indexing assignment requires a 0 or 1-dimensional input, input has 2 dimensions

### ISSUE THREAD

**Issue by lilykoff** [OxWearables/stepcount#53]
## Issue

Model fails to generate step counts/step times and returns `TypeError: NumPy boolean array indexing assignment requires a 0 or 1-dimensional input, input has 2 dimensions` 
The error happens for both the 'rf' and 'ssl' model versions, but not on the same datasets. 

## Reproducible example (SSL version) 

[Example dataset for SSL](https://github.com/OxWearables/stepcount/files/14117327/example_data_ssl.csv.gz)
The sample rate is 15Hz. 

### Command: 
```{bash}
$ conda activate stepcount
stepcount example_data_rf.csv.gz --model-type=ssl --sample-rate=15
```

### Output 
```{bash}
/Users/lilykoffman/anaconda3/envs/stepcount/lib/python3.9/site-packages/actipy/processing.py:294: UserWarning: Skipping calibration: Insufficient stationary samples: 0 < 50
  warnings.warn(f"Skipping calibration: Insufficient stationary samples: {len(xyz)} < {calib_min_samples}")
Gravity calibration... Done! (0.02s)
Nonwear detection... Done! (0.01s)
Resampling... Done! (0.03s)
Loading model...
Running step counter...
Defining windows...
100%|██████████████████████████████████████████████████████████████████████████| 58/58 [00:00<00:00, 862.53it/s]
Using local /Users/lilykoffman/anaconda3/envs/stepcount/lib/python3.9/site-packages/stepcount/torch_hub_cache/OxWearables_ssl-wearables_v1.0.0
Classifying windows...
100%|█████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.76it/s]
Traceback (most recent call last):
  File "/Users/lilykoffman/anaconda3/envs/stepcount/bin/stepcount", line 8, in <module>
    sys.exit(main())
  File "/Users/lilykoffman/anaconda3/envs/stepcount/lib/python3.9/site-packages/stepcount/stepcount.py", line 74, in main
    Y, W, T_steps = model.predict_from_frame(data)
  File "/Users/lilykoffman/anaconda3/envs/stepcount/lib/python3.9/site-packages/stepcount/models.py", line 243, in predict_from_frame
    Y, W, Z = self.predict(X, return_walk=True, return_step_times=True)
  File "/Users/lilykoffman/anaconda3/envs/stepcount/lib/python3.9/site-packages/stepcount/models.py", line 199, in predict
    (Y_[W_], Z_[W_]) = batch_count_peaks(
TypeError: NumPy boolean array indexing assignment requires a 0 or 1-dimensional input, input has 2 dimensions
```

## Reproducible example (RF version) 

[Example dataset for RF](https://github.com/OxWearables/stepcount/files/14117322/example_data_rf.csv.gz)
The sample rate is 15Hz.

### Command: 
```{bash}
$ conda activate stepcount
stepcount example_data_rf.csv.gz --model-type=rf --sample-rate=15
```

### Output
```{bash}
/Users/lilykoffman/anaconda3/envs/stepcount/lib/python3.9/site-packages/actipy/processing.py:294: UserWarning: Skipping calibration: Insufficient stationary samples: 0 < 50
  warnings.warn(f"Skipping calibration: Insufficient stationary samples: {len(xyz)} < {calib_min_samples}")
Gravity calibration... Done! (0.02s)
Nonwear detection... Done! (0.01s)
Loading model...
Running step counter...
Defining windows...
100%|███████████████████████████████████████████████████████████████████████| 147/147 [00:00<00:00, 2733.77it/s]
Extracting features...
100%|█████████████████████████████████████████████████████████████████████████| 146/146 [00:01<00:00, 86.02it/s]
Traceback (most recent call last):
  File "/Users/lilykoffman/anaconda3/envs/stepcount/bin/stepcount", line 8, in <module>
    sys.exit(main())
  File "/Users/lilykoffman/anaconda3/envs/stepcount/lib/python3.9/site-packages/stepcount/stepcount.py", line 74, in main
    Y, W, T_steps = model.predict_from_frame(data)
  File "/Users/lilykoffman/anaconda3/envs/stepcount/lib/python3.9/site-packages/stepcount/models.py", line 243, in predict_from_frame
    Y, W, Z = self.predict(X, return_walk=True, return_step_times=True)
  File "/Users/lilykoffman/anaconda3/envs/stepcount/lib/python3.9/site-packages/stepcount/models.py", line 199, in predict
    (Y_[W_], Z_[W_]) = batch_count_peaks(
TypeError: NumPy boolean array indexing assignment requires a 0 or 1-dimensional input, input has 2 dimensions
```

**Comment by chanshing** [comment]
Thanks for finding @lilykoff
I just pushed a fix. Can you update to v3.2.1 and test again?

```bash
pip install -U stepcount
```

**Comment by lilykoff** [comment]
works now, thanks!
