### ISSUE TITLE
ActiGraph .gt3x error

### ISSUE THREAD

**Issue by daslan29** [OxWearables/stepcount#58]
I am able to run stepcount on .cwa files but when I have tried running **stepcount on .gt3x files it does not work**. This Actigraph data was collected back in 2018.

It spends 15-20minutes "reading file..." 
Eported is dailySteps.csv, hourlySteps.csv, steps.csv, and time.csv but with no data in these csvs and no json and no adusted files

Have you seen this problem before? is there a workaround. 

I also have csv files with of the raw data x,y,z but it does not have a time column  but it does have the initial rows with the start time and start date (Would working with these files be easier)

Here is some meta data created from in the actigraph csv (not using for processing)  ActiGraph GT3X+ ActiLife v6.13.3 Firmware v1.9.2. 

Below is the error output

Reading file... Done! (2593.21s)
Converting to dataframe... Done! (8.32s)
Error: C:\Users\danas\AppData\Local\Temp\tmpthzt2197\data.npy - The process cannot access the file because it is being used by another process.
C:\Python310\lib\site-packages\actipy\processing.py:294: UserWarning: Skipping calibration: Insufficient stationary samples: 0 < 50
  warnings.warn(f"Skipping calibration: Insufficient stationary samples: {len(xyz)} < {calib_min_samples}")
Gravity calibration... Done! (20.16s)
Nonwear detection... Done! (15.73s)
Resampling... Done! (3.48s)
Loading model...
Running step counter...
Defining windows...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 498.85it/s]
Using local C:\Python310\lib\site-packages\stepcount\torch_hub_cache\OxWearables_ssl-wearables_v1.0.0
Classifying windows...
C:\Python310\lib\site-packages\numpy\core\fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Python310\lib\site-packages\numpy\core\_methods.py:192: RuntimeWarning: divide by zero encountered in divide
  ret = ret.dtype.type(ret / rcount)
C:\Python310\lib\site-packages\numpy\lib\nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
C:\Python310\lib\site-packages\numpy\core\fromnumeric.py:3464: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
C:\Python310\lib\site-packages\numpy\core\_methods.py:192: RuntimeWarning: divide by zero encountered in divide
  ret = ret.dtype.type(ret / rcount)
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\stepcount.exe\__main__.py", line 7, in <module>
  File "C:\Python310\lib\site-packages\stepcount\stepcount.py", line 105, in main
    summary_adj = summarize(Y, model.steptol, adjust_estimates=True)
  File "C:\Python310\lib\site-packages\stepcount\stepcount.py", line 146, in summarize
    Y = impute_missing(Y)
  File "C:\Python310\lib\site-packages\stepcount\stepcount.py", line 292, in impute_missing
    freq=to_offset(infer_freq(data.index)),
  File "pandas\_libs\tslibs\offsets.pyx", line 4102, in pandas._libs.tslibs.offsets.to_offset
  File "pandas\_libs\tslibs\offsets.pyx", line 4203, in pandas._libs.tslibs.offsets.to_offset
ValueError: Invalid frequency: NaT

**Comment by chanshing** [comment]
Hi @daslan29 Thanks for reporting this. We'll log this and make a plan to refactor the GT3X parser to make it more efficient, but don't have a timeline just yet.
In the meantime, I see you're preparsing it with another tool to extract the CSV file. From your description, you're having problems because the `time` column is missing. Anyway you can share a sample file so I can debug? Most likely we will need a way to impute the `time` column for all rows.

**Comment by daslan29** [comment]
Thank you Dr. Chan,

Attached is an sample CSV file 
[sampleActiGraph2.csv](https://github.com/OxWearables/stepcount/files/14168439/sampleActiGraph2.csv)

**Comment by chanshing** [comment]
Thanks!

I went through the file and we are currently not supporting that format yet, so you will have to manually reformat it beforehand.
Here is a script that should work at least on the file you shared:

[format_gt3xp.zip](https://github.com/OxWearables/stepcount/files/14212693/format_gt3xp.zip)

`python format_gt3xp.py /path/to/sampleActiGraph2.csv`

Let me know!
