### ISSUE TITLE
Period in filename causes failure

### ISSUE THREAD

**Issue by muschellij2** [OxWearables/stepcount#59]
If there are periods in the filename, there is going to be a failure likely as 
```bash
conda activate stepcount
wget https://github.com/OxWearables/stepcount/files/14117327/example_data_ssl.csv.gz -O example.data.csv.gz
stepcount example.data.csv.gz
```
```
Traceback (most recent call last):
  File "/Users/johnmuschelli/miniconda3/envs/stepcount/bin/stepcount", line 8, in <module>
    sys.exit(main())
  File "stepcount/stepcount.py", line 50, in main
    data, info = read(args.filepath, resample_hz, sample_rate=args.sample_rate, verbose=verbose)
  File "stepcount/stepcount.py", line 389, in read
    if 'ResampleRate' not in info:
UnboundLocalError: local variable 'info' referenced before assignment
```

This is due to parsing at https://github.com/OxWearables/stepcount/blob/85ee34db2bbdebdc53dfba6e7f9cf77897731f8c/src/stepcount/stepcount.py#L336
that does not generally handle suffixes if the filename has periods.

```python
import pathlib
filepath = "example.data.csv.gz"
p = pathlib.Path(filepath)
ftype = p.suffixes[0].lower()
ftype
p.suffixes
```

## Resolution
This may be resolved with using `p.suffixes`, but at least an `else` at the if statement of https://github.com/OxWearables/stepcount/blob/85ee34db2bbdebdc53dfba6e7f9cf77897731f8c/src/stepcount/stepcount.py#L378 so that an error "Failed to parse extension, getting .data (OR WHATEVER extension)".

```
$ python
Python 3.9.18 (main, Sep 11 2023, 08:38:23) 
[Clang 14.0.6 ] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pathlib
>>> filepath = "example.data.csv.gz"
>>> p = pathlib.Path(filepath)
>>> ftype = p.suffixes[0].lower()
>>> ftype
'.data'
>>> p.suffixes
['.data', '.csv', '.gz']

```

**Comment by chanshing** [comment]
Thanks for reporting this @muschellij2 !
