### ISSUE TITLE
Unable to read .csv files

### ISSUE THREAD

**Issue by freeman-jr1** [OxWearables/stepcount#61]
Hi,

I am trying to read an ActiGraph .csv file using stepcount version 3.2.3 and I am getting this error. 

```
Traceback (most recent call last):
  File "/home/freemanjr/.conda/envs/stepcount/bin/stepcount", line 8, in <module>
    sys.exit(main())
  File "/home/freemanjr/.conda/envs/stepcount/lib/python3.9/site-packages/stepcount/stepcount.py", line 50, in main
    data, info = read(args.filepath, resample_hz, sample_rate=args.sample_rate, verbose=verbose)
  File "/home/freemanjr/.conda/envs/stepcount/lib/python3.9/site-packages/stepcount/stepcount.py", line 357, in read
    freq = infer_freq(data.index)
  File "/home/freemanjr/.conda/envs/stepcount/lib/python3.9/site-packages/stepcount/stepcount.py", line 402, in infer_freq
    freq, _ = stats.mode(np.diff(x), keepdims=False)
  File "<__array_function__ internals>", line 200, in diff
  File "/home/freemanjr/.conda/envs/stepcount/lib/python3.9/site-packages/numpy/lib/function_base.py", line 1448, in diff
    a = op(a[slice1], a[slice2])
TypeError: unsupported operand type(s) for -: 'str' and 'str'

```
Any idea what may be going wrong here?

For additional clarification, this file has been successfully run using a previous version of stepcount and the column names are specified as time, x, y, z.

**Comment by aidendoherty** [comment]
Would it be possible to provide a sample of the first and last few lines of your input .csv file?
It looks like there may be a non-numeric value in one of the input columns

**Comment by freeman-jr1** [comment]
Hi @aidendoherty,

Thank you for the suggestion about the input columns. We think we may have found the issue. 

When examining this file and a separate file that worked, we noticed that the time column was stored differently. In the file that worked, the time column was stored as: 2024-02-09 10:00:08.000. The file that did not work was missing the decimal point and the milliseconds (.000). Adding in the decimal and milliseconds resulted in the file running.

Thank you for your help.
