### ISSUE TITLE
Failure with new `hmmlearn 0.3.0`

### ISSUE THREAD

**Issue by muschellij2** [OxWearables/stepcount#62]
Get errors with new `hmmlearn` and `rf` model: 
MultinomialHMM has undergone major changes. The previous version was implementing a CategoricalHMM (a special case of MultinomialHMM). This new implementation follows the standard definition for a Multinomial distribution (e.g. as in https://en.wikipedia.org/wiki/Multinomial_distribution). See these issues for details:
https://github.com/hmmlearn/hmmlearn/issues/335
https://github.com/hmmlearn/hmmlearn/issues/340

Traceback (most recent call last):
  File "/users/jmuschel/.conda/envs/stepcount/lib/python3.9/site-packages/stepcount/models.py", line 244, in predict_from_frame
    Y, W, Z = self.predict(X, return_walk=True, return_step_times=True)
  File "/users/jmuschel/.conda/envs/stepcount/lib/python3.9/site-packages/stepcount/models.py", line 195, in predict
    W_ = self.wd.predict(X_, groups).astype('bool')
  File "/users/jmuschel/.conda/envs/stepcount/lib/python3.9/site-packages/stepcount/models.py", line 358, in predict
    W = self.hmms.predict(W, groups=groups)
  File "/users/jmuschel/.conda/envs/stepcount/lib/python3.9/site-packages/stepcount/hmm_utils.py", line 48, in predict
    return self.hmmlearn_fit_predict(Y, groups=groups, method='predict')
  File "/users/jmuschel/.conda/envs/stepcount/lib/python3.9/site-packages/stepcount/hmm_utils.py", line 98, in hmmlearn_fit_predict
    _hmm, _score, _Y_pred = hmmlearn_fit_predict(Y[groups == g], groups=None, **hmm_params)
  File "/users/jmuschel/.conda/envs/stepcount/lib/python3.9/site-packages/stepcount/hmm_utils.py", line 195, in hmmlearn_fit_predict
    hmm.fit(Y_train, lengths_from_groups(groups_train))
  File "/users/jmuschel/.conda/envs/stepcount/lib/python3.9/site-packages/hmmlearn/base.py", line 468, in fit
  File "/users/jmuschel/.conda/envs/stepcount/lib/python3.9/site-packages/hmmlearn/hmm.py", line 895, in _init
    res = np.zeros((n_samples, self.n_components))
  File "/users/jmuschel/.conda/envs/stepcount/lib/python3.9/site-packages/hmmlearn/base.py", line 908, in _init
  File "/users/jmuschel/.conda/envs/stepcount/lib/python3.9/site-packages/hmmlearn/_emissions.py", line 317, in _check_and_set_n_features
  File "/users/jmuschel/.conda/envs/stepcount/lib/python3.9/site-packages/hmmlearn/base.py", line 527, in _check_and_set_n_features
    "transition from the state was ever observed.")
ValueError: Unexpected number of dimensions, got 1 but expected 2

Reverting to 0.2.7 fixed this.

**Comment by muschellij2** [comment]
Only fails for the `rf` model.
Example file
[example.data.csv](https://github.com/OxWearables/stepcount/files/14188564/example.data.csv)

## Example Script
```
conda activate stepcount
pip install --upgrade stepcount
pip uninstall -y hmmlearn
pip install hmmlearn==0.3.0
conda list stepcount 
conda list hmmlearn 

stepcount example.data.csv
rm -rf outputs
stepcount --model-type rf example.data.csv
rm -rf outputs

pip uninstall -y hmmlearn
pip install --upgrade stepcount
pip install hmmlearn==0.2.7
conda list stepcount 
conda list hmmlearn 
stepcount example.data.csv
rm -rf outputs
stepcount --model-type rf example.data.csv
rm -rf outputs
```


## Output

```
Requirement already satisfied: stepcount in /stepcount/lib/python3.9/site-packages (3.2.3)
Requirement already satisfied: actipy>=3.0.5 in /stepcount/lib/python3.9/site-packages (from stepcount) (3.0.5)
Requirement already satisfied: numpy==1.24.* in /stepcount/lib/python3.9/site-packages (from stepcount) (1.24.4)
Requirement already satisfied: scipy==1.10.* in /stepcount/lib/python3.9/site-packages (from stepcount) (1.10.1)
Requirement already satisfied: pandas==2.0.* in /stepcount/lib/python3.9/site-packages (from stepcount) (2.0.3)
Requirement already satisfied: tqdm==4.64.* in /stepcount/lib/python3.9/site-packages (from stepcount) (4.64.1)
Requirement already satisfied: joblib==1.2.* in /stepcount/lib/python3.9/site-packages (from stepcount) (1.2.0)
Requirement already satisfied: scikit-learn==1.1.1 in /stepcount/lib/python3.9/site-packages (from stepcount) (1.1.1)
Requirement already satisfied: imbalanced-learn==0.9.1 in /stepcount/lib/python3.9/site-packages (from stepcount) (0.9.1)
Requirement already satisfied: hmmlearn==0.3.* in /stepcount/lib/python3.9/site-packages (from stepcount) (0.3.0)
Requirement already satisfied: torch==1.13.* in /stepcount/lib/python3.9/site-packages (from stepcount) (1.13.1)
Requirement already satisfied: torchvision==0.14.* in /stepcount/lib/python3.9/site-packages (from stepcount) (0.14.1)
Requirement already satisfied: transforms3d==0.4.* in /stepcount/lib/python3.9/site-packages (from stepcount) (0.4.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /stepcount/lib/python3.9/site-packages (from imbalanced-learn==0.9.1->stepcount) (3.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /stepcount/lib/python3.9/site-packages (from pandas==2.0.*->stepcount) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /stepcount/lib/python3.9/site-packages (from pandas==2.0.*->stepcount) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /stepcount/lib/python3.9/site-packages (from pandas==2.0.*->stepcount) (2023.3)
Requirement already satisfied: typing-extensions in /stepcount/lib/python3.9/site-packages (from torch==1.13.*->stepcount) (4.9.0)
Requirement already satisfied: requests in /stepcount/lib/python3.9/site-packages (from torchvision==0.14.*->stepcount) (2.31.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /stepcount/lib/python3.9/site-packages (from torchvision==0.14.*->stepcount) (10.1.0)
Requirement already satisfied: statsmodels>=0.13 in /stepcount/lib/python3.9/site-packages (from actipy>=3.0.5->stepcount) (0.14.0)
Requirement already satisfied: six>=1.5 in /stepcount/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas==2.0.*->stepcount) (1.16.0)
Requirement already satisfied: patsy>=0.5.2 in /stepcount/lib/python3.9/site-packages (from statsmodels>=0.13->actipy>=3.0.5->stepcount) (0.5.4)
Requirement already satisfied: packaging>=21.3 in /stepcount/lib/python3.9/site-packages (from statsmodels>=0.13->actipy>=3.0.5->stepcount) (23.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /stepcount/lib/python3.9/site-packages (from requests->torchvision==0.14.*->stepcount) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /stepcount/lib/python3.9/site-packages (from requests->torchvision==0.14.*->stepcount) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /stepcount/lib/python3.9/site-packages (from requests->torchvision==0.14.*->stepcount) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /stepcount/lib/python3.9/site-packages (from requests->torchvision==0.14.*->stepcount) (2023.11.17)
Found existing installation: hmmlearn 0.3.0
Uninstalling hmmlearn-0.3.0:
  Successfully uninstalled hmmlearn-0.3.0
Collecting hmmlearn==0.3.0
  Using cached hmmlearn-0.3.0-cp39-cp39-macosx_10_9_x86_64.whl (128 kB)
Requirement already satisfied: numpy>=1.10 in /stepcount/lib/python3.9/site-packages (from hmmlearn==0.3.0) (1.24.4)
Requirement already satisfied: scikit-learn!=0.22.0,>=0.16 in /stepcount/lib/python3.9/site-packages (from hmmlearn==0.3.0) (1.1.1)
Requirement already satisfied: scipy>=0.19 in /stepcount/lib/python3.9/site-packages (from hmmlearn==0.3.0) (1.10.1)
Requirement already satisfied: joblib>=1.0.0 in /stepcount/lib/python3.9/site-packages (from scikit-learn!=0.22.0,>=0.16->hmmlearn==0.3.0) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /stepcount/lib/python3.9/site-packages (from scikit-learn!=0.22.0,>=0.16->hmmlearn==0.3.0) (3.2.0)
Installing collected packages: hmmlearn
Successfully installed hmmlearn-0.3.0
# packages in environment at /stepcount:
#
# Name                    Version                   Build  Channel
stepcount                 3.2.3                    pypi_0    pypi
/stepcount/lib/python3.9/site-packages/actipy/processing.py:294: UserWarning: Skipping calibration: Insufficient stationary samples: 0 < 50
  warnings.warn(f"Skipping calibration: Insufficient stationary samples: {len(xyz)} < {calib_min_samples}")
Gravity calibration... Done! (0.01s)
Nonwear detection... Done! (0.01s)
Resampling... Done! (0.03s)
Loading model...
Running step counter...
Defining windows...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 58/58 [00:00<00:00, 2246.42it/s]
Using local /stepcount/lib/python3.9/site-packages/stepcount/torch_hub_cache/OxWearables_ssl-wearables_v1.0.0
Classifying windows...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.00it/s]
/stepcount/lib/python3.9/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/stepcount/lib/python3.9/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

Summary
-------
{
    "Filename": "example.data.csv.gz",
    "Device": ".csv",
    "Filesize(MB)": 0.1,
    "SampleRate": 15,
    "CalibOK": 0,
    "CalibErrorBefore(mg)": NaN,
    "CalibErrorAfter(mg)": NaN,
    "WearTime(days)": 0.006696736111111111,
    "NonwearTime(days)": 0.0,
    "NumNonwearEpisodes": 0,
    "ResampleRate": 30,
    "NumTicksAfterResample": 17359,
    "TotalSteps": 14,
    "StepsDayAvg": 14,
    "StepsDayMed": 14,
    "StepsDayMin": 14,
    "StepsDayMax": 14,
    "TotalWalking(mins)": 0,
    "WalkingDayAvg(mins)": 0,
    "WalkingDayMed(mins)": 0,
    "WalkingDayMin(mins)": 0,
    "WalkingDayMax(mins)": 0,
    "CadencePeak1(steps/min)": 14,
    "CadencePeak30(steps/min)": 1,
    "StepsQ1DayAvgAt": "10:00:00",
    "StepsQ2DayAvgAt": "10:00:00",
    "StepsQ3DayAvgAt": "10:00:00",
    "StepsQ1DayMedAt": "10:00:00",
    "StepsQ2DayMedAt": "10:00:00",
    "StepsQ3DayMedAt": "10:00:00",
    "TotalStepsAdjusted": NaN,
    "StepsDayAvgAdjusted": NaN,
    "StepsDayMedAdjusted": NaN,
    "StepsDayMinAdjusted": NaN,
    "StepsDayMaxAdjusted": NaN,
    "TotalWalkingAdjusted(mins)": NaN,
    "WalkingDayAvgAdjusted(mins)": NaN,
    "WalkingDayMedAdjusted(mins)": NaN,
    "WalkingDayMinAdjusted(mins)": NaN,
    "WalkingDayMaxAdjusted(mins)": NaN,
    "CadencePeak1Adjusted(steps/min)": 84,
    "CadencePeak30Adjusted(steps/min)": 0,
    "StepsQ1DayAvgAdjustedAt": NaN,
    "StepsQ2DayAvgAdjustedAt": NaN,
    "StepsQ3DayAvgAdjustedAt": NaN,
    "StepsQ1DayMedAdjustedAt": NaN,
    "StepsQ2DayMedAdjustedAt": NaN,
    "StepsQ3DayMedAdjustedAt": NaN
}

Estimated Daily Stats
---------------------
            Walk(mins)  Steps StepsQ1At StepsQ2At StepsQ3At
time                                                       
2023-10-23         0.0   14.0  10:00:00  10:00:00  10:00:00

Estimated Daily Stats (Adjusted)
---------------------
            Walk(mins)  Steps  StepsQ1At  StepsQ2At  StepsQ3At
time                                                          
2023-10-23         NaN    NaN        NaN        NaN        NaN
Done! (5.69s)
/stepcount/lib/python3.9/site-packages/actipy/processing.py:294: UserWarning: Skipping calibration: Insufficient stationary samples: 0 < 50
  warnings.warn(f"Skipping calibration: Insufficient stationary samples: {len(xyz)} < {calib_min_samples}")
Gravity calibration... Done! (0.01s)
Nonwear detection... Done! (0.00s)
Loading model...
Running step counter...
Defining windows...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 116/116 [00:00<00:00, 2464.84it/s]
Extracting features...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 116/116 [00:01<00:00, 98.27it/s]
MultinomialHMM has undergone major changes. The previous version was implementing a CategoricalHMM (a special case of MultinomialHMM). This new implementation follows the standard definition for a Multinomial distribution (e.g. as in https://en.wikipedia.org/wiki/Multinomial_distribution). See these issues for details:
https://github.com/hmmlearn/hmmlearn/issues/335
https://github.com/hmmlearn/hmmlearn/issues/340
Traceback (most recent call last):
  File "/stepcount/bin/stepcount", line 8, in <module>
    sys.exit(main())
  File "/stepcount/lib/python3.9/site-packages/stepcount/stepcount.py", line 74, in main
    Y, W, T_steps = model.predict_from_frame(data)
  File "/stepcount/lib/python3.9/site-packages/stepcount/models.py", line 244, in predict_from_frame
    Y, W, Z = self.predict(X, return_walk=True, return_step_times=True)
  File "/stepcount/lib/python3.9/site-packages/stepcount/models.py", line 195, in predict
    W_ = self.wd.predict(X_, groups).astype('bool')
  File "/stepcount/lib/python3.9/site-packages/stepcount/models.py", line 358, in predict
    W = self.hmms.predict(W, groups=groups)
  File "/stepcount/lib/python3.9/site-packages/stepcount/hmm_utils.py", line 48, in predict
    return self.hmmlearn_fit_predict(Y, groups=groups, method='predict')
  File "/stepcount/lib/python3.9/site-packages/stepcount/hmm_utils.py", line 98, in hmmlearn_fit_predict
    _hmm, _score, _Y_pred = hmmlearn_fit_predict(Y[groups == g], groups=None, **hmm_params)
  File "/stepcount/lib/python3.9/site-packages/stepcount/hmm_utils.py", line 195, in hmmlearn_fit_predict
    hmm.fit(Y_train, lengths_from_groups(groups_train))
  File "/stepcount/lib/python3.9/site-packages/hmmlearn/base.py", line 468, in fit
    self._init(X, lengths)
  File "/stepcount/lib/python3.9/site-packages/hmmlearn/hmm.py", line 895, in _init
    super()._init(X, lengths=None)
  File "/stepcount/lib/python3.9/site-packages/hmmlearn/base.py", line 908, in _init
    self._check_and_set_n_features(X)
  File "/stepcount/lib/python3.9/site-packages/hmmlearn/_emissions.py", line 317, in _check_and_set_n_features
    super()._check_and_set_n_features(X)
  File "/stepcount/lib/python3.9/site-packages/hmmlearn/base.py", line 527, in _check_and_set_n_features
    raise ValueError(
ValueError: Unexpected number of dimensions, got 1 but expected 2
```


Here is the code with the hmmlearn 0.27 and stepcount 3.2.3

```
Found existing installation: hmmlearn 0.3.0
Uninstalling hmmlearn-0.3.0:
  Successfully uninstalled hmmlearn-0.3.0
Requirement already satisfied: stepcount in /stepcount/lib/python3.9/site-packages (3.2.3)
Requirement already satisfied: actipy>=3.0.5 in /stepcount/lib/python3.9/site-packages (from stepcount) (3.0.5)
Requirement already satisfied: numpy==1.24.* in /stepcount/lib/python3.9/site-packages (from stepcount) (1.24.4)
Requirement already satisfied: scipy==1.10.* in /stepcount/lib/python3.9/site-packages (from stepcount) (1.10.1)
Requirement already satisfied: pandas==2.0.* in /stepcount/lib/python3.9/site-packages (from stepcount) (2.0.3)
Requirement already satisfied: tqdm==4.64.* in /stepcount/lib/python3.9/site-packages (from stepcount) (4.64.1)
Requirement already satisfied: joblib==1.2.* in /stepcount/lib/python3.9/site-packages (from stepcount) (1.2.0)
Requirement already satisfied: scikit-learn==1.1.1 in /stepcount/lib/python3.9/site-packages (from stepcount) (1.1.1)
Requirement already satisfied: imbalanced-learn==0.9.1 in /stepcount/lib/python3.9/site-packages (from stepcount) (0.9.1)
Collecting hmmlearn==0.3.* (from stepcount)
  Using cached hmmlearn-0.3.0-cp39-cp39-macosx_10_9_x86_64.whl (128 kB)
Requirement already satisfied: torch==1.13.* in /stepcount/lib/python3.9/site-packages (from stepcount) (1.13.1)
Requirement already satisfied: torchvision==0.14.* in /stepcount/lib/python3.9/site-packages (from stepcount) (0.14.1)
Requirement already satisfied: transforms3d==0.4.* in /stepcount/lib/python3.9/site-packages (from stepcount) (0.4.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /stepcount/lib/python3.9/site-packages (from imbalanced-learn==0.9.1->stepcount) (3.2.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /stepcount/lib/python3.9/site-packages (from pandas==2.0.*->stepcount) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /stepcount/lib/python3.9/site-packages (from pandas==2.0.*->stepcount) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /stepcount/lib/python3.9/site-packages (from pandas==2.0.*->stepcount) (2023.3)
Requirement already satisfied: typing-extensions in /stepcount/lib/python3.9/site-packages (from torch==1.13.*->stepcount) (4.9.0)
Requirement already satisfied: requests in /stepcount/lib/python3.9/site-packages (from torchvision==0.14.*->stepcount) (2.31.0)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in /stepcount/lib/python3.9/site-packages (from torchvision==0.14.*->stepcount) (10.1.0)
Requirement already satisfied: statsmodels>=0.13 in /stepcount/lib/python3.9/site-packages (from actipy>=3.0.5->stepcount) (0.14.0)
Requirement already satisfied: six>=1.5 in /stepcount/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas==2.0.*->stepcount) (1.16.0)
Requirement already satisfied: patsy>=0.5.2 in /stepcount/lib/python3.9/site-packages (from statsmodels>=0.13->actipy>=3.0.5->stepcount) (0.5.4)
Requirement already satisfied: packaging>=21.3 in /stepcount/lib/python3.9/site-packages (from statsmodels>=0.13->actipy>=3.0.5->stepcount) (23.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /stepcount/lib/python3.9/site-packages (from requests->torchvision==0.14.*->stepcount) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /stepcount/lib/python3.9/site-packages (from requests->torchvision==0.14.*->stepcount) (3.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in /stepcount/lib/python3.9/site-packages (from requests->torchvision==0.14.*->stepcount) (2.1.0)
Requirement already satisfied: certifi>=2017.4.17 in /stepcount/lib/python3.9/site-packages (from requests->torchvision==0.14.*->stepcount) (2023.11.17)
Installing collected packages: hmmlearn
Successfully installed hmmlearn-0.3.0
Collecting hmmlearn==0.2.7
  Using cached hmmlearn-0.2.7-cp39-cp39-macosx_10_15_x86_64.whl (101 kB)
Requirement already satisfied: numpy>=1.10 in /stepcount/lib/python3.9/site-packages (from hmmlearn==0.2.7) (1.24.4)
Requirement already satisfied: scikit-learn>=0.16 in /stepcount/lib/python3.9/site-packages (from hmmlearn==0.2.7) (1.1.1)
Requirement already satisfied: scipy>=0.19 in /stepcount/lib/python3.9/site-packages (from hmmlearn==0.2.7) (1.10.1)
Requirement already satisfied: joblib>=1.0.0 in /stepcount/lib/python3.9/site-packages (from scikit-learn>=0.16->hmmlearn==0.2.7) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in /stepcount/lib/python3.9/site-packages (from scikit-learn>=0.16->hmmlearn==0.2.7) (3.2.0)
Installing collected packages: hmmlearn
  Attempting uninstall: hmmlearn
    Found existing installation: hmmlearn 0.3.0
    Uninstalling hmmlearn-0.3.0:
      Successfully uninstalled hmmlearn-0.3.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
stepcount 3.2.3 requires hmmlearn==0.3.*, but you have hmmlearn 0.2.7 which is incompatible.
Successfully installed hmmlearn-0.2.7
# packages in environment at /stepcount:
#
# Name                    Version                   Build  Channel
stepcount                 3.2.3                    pypi_0    pypi
# packages in environment at /stepcount:
#
# Name                    Version                   Build  Channel
hmmlearn                  0.2.7                    pypi_0    pypi
/stepcount/lib/python3.9/site-packages/actipy/processing.py:294: UserWarning: Skipping calibration: Insufficient stationary samples: 0 < 50
  warnings.warn(f"Skipping calibration: Insufficient stationary samples: {len(xyz)} < {calib_min_samples}")
Gravity calibration... Done! (0.01s)
Nonwear detection... Done! (0.01s)
Resampling... Done! (0.05s)
Loading model...
Running step counter...
Defining windows...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 58/58 [00:00<00:00, 2235.58it/s]
Using local /stepcount/lib/python3.9/site-packages/stepcount/torch_hub_cache/OxWearables_ssl-wearables_v1.0.0
Classifying windows...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.05it/s]
/stepcount/lib/python3.9/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/stepcount/lib/python3.9/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

Summary
-------
{
    "Filename": "example.data.csv.gz",
    "Device": ".csv",
    "Filesize(MB)": 0.1,
    "SampleRate": 15,
    "CalibOK": 0,
    "CalibErrorBefore(mg)": NaN,
    "CalibErrorAfter(mg)": NaN,
    "WearTime(days)": 0.006696736111111111,
    "NonwearTime(days)": 0.0,
    "NumNonwearEpisodes": 0,
    "ResampleRate": 30,
    "NumTicksAfterResample": 17359,
    "TotalSteps": 14,
    "StepsDayAvg": 14,
    "StepsDayMed": 14,
    "StepsDayMin": 14,
    "StepsDayMax": 14,
    "TotalWalking(mins)": 0,
    "WalkingDayAvg(mins)": 0,
    "WalkingDayMed(mins)": 0,
    "WalkingDayMin(mins)": 0,
    "WalkingDayMax(mins)": 0,
    "CadencePeak1(steps/min)": 14,
    "CadencePeak30(steps/min)": 1,
    "StepsQ1DayAvgAt": "10:00:00",
    "StepsQ2DayAvgAt": "10:00:00",
    "StepsQ3DayAvgAt": "10:00:00",
    "StepsQ1DayMedAt": "10:00:00",
    "StepsQ2DayMedAt": "10:00:00",
    "StepsQ3DayMedAt": "10:00:00",
    "TotalStepsAdjusted": NaN,
    "StepsDayAvgAdjusted": NaN,
    "StepsDayMedAdjusted": NaN,
    "StepsDayMinAdjusted": NaN,
    "StepsDayMaxAdjusted": NaN,
    "TotalWalkingAdjusted(mins)": NaN,
    "WalkingDayAvgAdjusted(mins)": NaN,
    "WalkingDayMedAdjusted(mins)": NaN,
    "WalkingDayMinAdjusted(mins)": NaN,
    "WalkingDayMaxAdjusted(mins)": NaN,
    "CadencePeak1Adjusted(steps/min)": 84,
    "CadencePeak30Adjusted(steps/min)": 0,
    "StepsQ1DayAvgAdjustedAt": NaN,
    "StepsQ2DayAvgAdjustedAt": NaN,
    "StepsQ3DayAvgAdjustedAt": NaN,
    "StepsQ1DayMedAdjustedAt": NaN,
    "StepsQ2DayMedAdjustedAt": NaN,
    "StepsQ3DayMedAdjustedAt": NaN
}

Estimated Daily Stats
---------------------
            Walk(mins)  Steps StepsQ1At StepsQ2At StepsQ3At
time                                                       
2023-10-23         0.0   14.0  10:00:00  10:00:00  10:00:00

Estimated Daily Stats (Adjusted)
---------------------
            Walk(mins)  Steps  StepsQ1At  StepsQ2At  StepsQ3At
time                                                          
2023-10-23         NaN    NaN        NaN        NaN        NaN
Done! (5.44s)
/stepcount/lib/python3.9/site-packages/actipy/processing.py:294: UserWarning: Skipping calibration: Insufficient stationary samples: 0 < 50
  warnings.warn(f"Skipping calibration: Insufficient stationary samples: {len(xyz)} < {calib_min_samples}")
Gravity calibration... Done! (0.01s)
Nonwear detection... Done! (0.01s)
Loading model...
Running step counter...
Defining windows...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 116/116 [00:00<00:00, 2515.47it/s]
Extracting features...
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████| 116/116 [00:01<00:00, 90.35it/s]
/stepcount/lib/python3.9/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)
/stepcount/lib/python3.9/site-packages/numpy/lib/nanfunctions.py:1215: RuntimeWarning: Mean of empty slice
  return np.nanmean(a, axis, out=out, keepdims=keepdims)

Summary
-------
{
    "Filename": "example.data.csv.gz",
    "Device": ".csv",
    "Filesize(MB)": 0.1,
    "SampleRate": 15,
    "CalibOK": 0,
    "CalibErrorBefore(mg)": NaN,
    "CalibErrorAfter(mg)": NaN,
    "WearTime(days)": 0.006696736111111111,
    "NonwearTime(days)": 0.0,
    "NumNonwearEpisodes": 0,
    "ResampleRate": 15,
    "TotalSteps": 18,
    "StepsDayAvg": 18,
    "StepsDayMed": 18,
    "StepsDayMin": 18,
    "StepsDayMax": 18,
    "TotalWalking(mins)": 0,
    "WalkingDayAvg(mins)": 0,
    "WalkingDayMed(mins)": 0,
    "WalkingDayMin(mins)": 0,
    "WalkingDayMax(mins)": 0,
    "CadencePeak1(steps/min)": 18,
    "CadencePeak30(steps/min)": 2,
    "StepsQ1DayAvgAt": "10:00:00",
    "StepsQ2DayAvgAt": "10:00:05",
    "StepsQ3DayAvgAt": "10:00:10",
    "StepsQ1DayMedAt": "10:00:00",
    "StepsQ2DayMedAt": "10:00:05",
    "StepsQ3DayMedAt": "10:00:10",
    "TotalStepsAdjusted": NaN,
    "StepsDayAvgAdjusted": NaN,
    "StepsDayMedAdjusted": NaN,
    "StepsDayMinAdjusted": NaN,
    "StepsDayMaxAdjusted": NaN,
    "TotalWalkingAdjusted(mins)": NaN,
    "WalkingDayAvgAdjusted(mins)": NaN,
    "WalkingDayMedAdjusted(mins)": NaN,
    "WalkingDayMinAdjusted(mins)": NaN,
    "WalkingDayMaxAdjusted(mins)": NaN,
    "CadencePeak1Adjusted(steps/min)": 84,
    "CadencePeak30Adjusted(steps/min)": 0,
    "StepsQ1DayAvgAdjustedAt": NaN,
    "StepsQ2DayAvgAdjustedAt": NaN,
    "StepsQ3DayAvgAdjustedAt": NaN,
    "StepsQ1DayMedAdjustedAt": NaN,
    "StepsQ2DayMedAdjustedAt": NaN,
    "StepsQ3DayMedAdjustedAt": NaN
}

Estimated Daily Stats
---------------------
            Walk(mins)  Steps StepsQ1At StepsQ2At StepsQ3At
time                                                       
2023-10-23         0.0   18.0  10:00:00  10:00:05  10:00:10

Estimated Daily Stats (Adjusted)
---------------------
            Walk(mins)  Steps  StepsQ1At  StepsQ2At  StepsQ3At
time                                                          
2023-10-23         NaN    NaN        NaN        NaN        NaN
Done! (8.39s)
```

**Comment by chanshing** [comment]
Thanks @muschellij2 again!
I just fixed this in https://github.com/OxWearables/stepcount/pull/63
I updated the module name accordingly. We're keeping the version to 0.3.0 as it is needed for MacOS systems https://github.com/OxWearables/stepcount/issues/33
